### ISSUE TITLE
Pinned tabs not rendering correctly

### ISSUE THREAD

**Issue by pratyush3757** [manilarome/blurredfox#10]
Pinned tabs disappear and when the window is tiled left/right to half screen. And a blank space is left in their place.
![Screenshot_20200730_170632](https://user-images.githubusercontent.com/41483445/88918430-0be20080-d287-11ea-8c16-9068230a3085.png)

![Screenshot_20200730_170528](https://user-images.githubusercontent.com/41483445/88918368-f371e600-d286-11ea-90b2-b88cbff70c98.png)

**Comment by pratyush3757** [comment]
I've also noticed that the icons for the pinned tabs are rendered next to left arrow when they appear as seen in the 1st picture

**Comment by manilarome** [comment]
Confirmed, can also reproduced this. Will work on it later! Just busy right now.

**Comment by manilarome** [comment]
Done! https://github.com/manilarome/blurredfox/commit/4384e6865886c4e3ba3ea9b6100420de489c35b9 fixes this. Closing this now. Thanks for reporting!


![20200802_153138](https://user-images.githubusercontent.com/40349590/89118299-388c5700-d4d7-11ea-94fa-1ede8aa71415.png)
