### ISSUE TITLE
 MacOS - window controls moved down with the tab bar

### ISSUE THREAD

**Issue by jonaylor89** [manilarome/blurredfox#12]
<img width="1440" alt="Screen Shot 2020-08-08 at 12 49 38 PM" src="https://user-images.githubusercontent.com/17736112/89715719-a45a3e00-d975-11ea-9b3e-8e6b61530aa3.png">

The only fix I have right now is to just move the tab bar back above the url bar

**Comment by manilarome** [comment]
This theme is untested in macOS, but you can move the navbar on top again by switching the comments here:

https://github.com/manilarome/blurredfox/blob/a1a4a231e27555135105e2f05bbe20013dea3505/userChrome.css#L352-L353
