### ISSUE TITLE
Firefox Dev compatibility

### ISSUE THREAD

**Issue by PoSayDone** [manilarome/blurredfox#13]
Hi! How I could make it work in firefox dev edition?

**Comment by PoSayDone** [comment]
Now theme is working, but blur isn't 
![image](https://user-images.githubusercontent.com/29358657/89730734-0b9dee00-da5b-11ea-9369-5116fc9afaa0.png)

**Comment by manilarome** [comment]
> Now theme is working, but blur isn't

As I've said on my post and in the README, you need a compositor for the blur. Note that there's a guide in the README for the KDE Plasma users. That's all the help I can give you because I don't use Plasma and cannot test it. Closing this now. Good luck !
