### ISSUE TITLE
Does it work for Firefox Developer?

### ISSUE THREAD

**Issue by yizongk** [manilarome/blurredfox#18]
I am trying to install for Firefox Developer, but when I run
```
 bash -c "$(curl -fsSL https://raw.githubusercontent.com/manilarome/blurredfox/master/install.sh)"
```
It's returning
```
[!!] No firefox user profile directory found. Make sure to run firefox atleast once! Terminating...
```

Does blurredfox support FireFox Developer edition?

**Comment by manilarome** [comment]
> Does blurredfox support FireFox Developer edition?

Yes! It does!

![image](https://user-images.githubusercontent.com/40349590/90213168-a74aa800-de27-11ea-9af0-4929f0754e32.png)


Note that the installation script does not support dev edition at the moment. So use the manual installation one.

**Comment by PoorPocketsMcNewHold** [comment]
I´ll like to also add, that it does work under Firefox Nightly too, despite not being supported by the bash installer as well.

**Comment by manilarome** [comment]
> I´ll like to also add, that it does work under Firefox Nightly too, despite not being supported by the bash installer as well.

Thanks for the input! I'll try to support these releases.

**Comment by manilarome** [comment]
Closing this now. I'll just create a new issue about the installer script.
