### ISSUE TITLE
Menu bar has poor contrast

### ISSUE THREAD

**Issue by gabrc52** [manilarome/blurredfox#2]
File, Edit are barely readable

![image](https://user-images.githubusercontent.com/24363938/82843123-caf1f800-9ea1-11ea-8598-857bb8b0ea48.png)

**Comment by manilarome** [comment]
The problem is the transparency. I forgot to add one for the menubar(and bookmark bar). Anyway thanks for reporting. Will try to fix this later.

**Comment by manilarome** [comment]
![image](https://user-images.githubusercontent.com/40349590/82848003-e271c500-9f23-11ea-816c-a9614aa12431.png)

Done https://github.com/manilarome/blurredfox/commit/8dfd658e48580b5ffecdc6bf395bf3f133aa2894

**Comment by gabrc52** [comment]
Awesome, thanks a lot! That was extremely quick!
