### ISSUE TITLE
Support for Color coding of container tabs

### ISSUE THREAD

**Issue by AshutoshFreak** [manilarome/blurredfox#22]
This theme looks super cool on my KDE. But I cannot see the color coding support for Container tabs. Can you please add it?

This is how it looks right now (blurredfox theme):
![new](https://user-images.githubusercontent.com/44664726/90313111-836e8b80-df27-11ea-813c-95478d719cd8.png)

This is how tabs are color coded when in container (Default Firefox theme):
![old](https://user-images.githubusercontent.com/44664726/90313172-f841c580-df27-11ea-9257-2d2d568514c6.png)

There's another theme that I've been using which color codes containers by dots ([Sweet Theme](https://github.com/EliverLara/firefox-sweet-theme)):
![new1](https://user-images.githubusercontent.com/44664726/90313350-75216f00-df29-11ea-9c5e-bb94c7a66579.png)

**Comment by manilarome** [comment]
Thanks for reporting this! This [commit](https://github.com/manilarome/blurredfox/commit/0013f6eda52f29a6525a6cc8a1d73c11449d5024) fixed this!
