### ISSUE TITLE
New Tab is set to white theme

### ISSUE THREAD

**Issue by Adaoh2** [manilarome/blurredfox#23]
![Screenshot_20200815_170338](https://user-images.githubusercontent.com/43153657/90321647-9e3a0380-df19-11ea-97da-a0597ceac4f5.png)
The new tab background is white as shown in the picture. The theme is set to dark mode, so I do not know what causes this.

**Comment by manilarome** [comment]
Hi! Thanks for reporting this. This [commit](https://github.com/manilarome/blurredfox/commit/fe717e97cf5269761d1c3b4f9eef40f4e81cec1e) should fixed this!
