### ISSUE TITLE
Missing microphone, webcam permission and tracker protection icons 

### ISSUE THREAD

**Issue by AshutoshFreak** [manilarome/blurredfox#27]
I cannot find permission and tracker protection icons in blurredfox theme. So, I'm not able to take back the permission for microphone after giving it for the first time. Also, I'm not able to see the list of trackers deployed on a website. They should look something like this (from default firefox theme):
![Screenshot_20200817_112652](https://user-images.githubusercontent.com/44664726/90361977-2389f900-e07d-11ea-80fa-884e434d82da.png)

**Comment by manilarome** [comment]
They are [disabled](https://github.com/manilarome/blurredfox/blob/d08acf55b5ac499ba5fb0355b004001258d2c1f1/parts/urlbar.css#L192-L200). Just comment those lines.

**Comment by manilarome** [comment]
https://github.com/manilarome/blurredfox/commit/492caf6415237631923482428188ca3affd31422 fixes this. I also added border radius to them for consistency. Thanks for reporting!
