### ISSUE TITLE
Too small URL bar

### ISSUE THREAD

**Issue by AshutoshFreak** [manilarome/blurredfox#28]
Thank you for the quick fixes of the previous issues that I opened. I ran into another problem and would like to report it.
When the window covers half of my desktop screen (which is pretty common), URL bar becomes too small to show the URL of a website. I can barely click to enter a new URL or bookmark a site.

![Screenshot_20200817_112652](https://user-images.githubusercontent.com/44664726/90372174-98fdc580-e08d-11ea-81fe-52a0e8b4e985.png)

Perhaps when the window size is small, making use of the blank space present before and after of the URL bar may help.

**Comment by manilarome** [comment]
> Thank you for the quick fixes of the previous issues that I opened. I ran into another problem and would like to report it.


No problem.

> URL bar too small


Well, I cannot really "fix" this. People with widescreen screen are definitely will not have a "shortage" of urlbar. You can just edit the width of it in ```urlbar.css```.

**Comment by AshutoshFreak** [comment]
Thank you! I'll give it a try

**Comment by manilarome** [comment]
No problem! Good luck! Closing this now.
