### ISSUE TITLE
Traffic light buttons (close, minimize, maximize) buttons not on left on macOS

### ISSUE THREAD

**Issue by AlphaRacer** [manilarome/blurredfox#29]
<img width="1438" alt="Screenshot 2020-08-21 at 11 53 13 AM" src="https://user-images.githubusercontent.com/61911772/90859087-22223e80-e3a5-11ea-8e9b-e9916897a135.png">

The traffic light buttons (close, minimize, maximize) are not on the left of the window like seen in the product's screenshots.

Is this a bug?

**Comment by manilarome** [comment]
> The traffic light buttons (close, minimize, maximize) are not on the left of the window like seen in the product's screenshots. Is this a bug?

The titlebar on the left side of the window is from `awesome wm`, a window manager on Linux. So yeah, it's not included in the CSS theme. I don't know if it's possible on mac tho. Closing this now!
