### ISSUE TITLE
Gap on tab bar

### ISSUE THREAD

**Issue by gabrc52** [manilarome/blurredfox#3]
On top right corner, below the hamburger menu, there's a gap

![image](https://user-images.githubusercontent.com/24363938/82843210-0ee4fd00-9ea2-11ea-9ce7-9919b1471223.png)

**Comment by manilarome** [comment]
Weird, can't reproduce this. Uhm are you on private window?

**Comment by gabrc52** [comment]
I'm using KDE's Kwin, in regular mode

**Comment by manilarome** [comment]
Okay, thanks.  Can you please check it again? On your [other post](https://github.com/manilarome/blurredfox/issues/2), there's no gap, and I can't really reproduce this. I'm using `Mozilla Firefox 76.0.1`

**Comment by gabrc52** [comment]
I've performed an update and it doesn't happen anymore. It was probably my out of date Firefox
