### ISSUE TITLE
Scroll bar missing

### ISSUE THREAD

**Issue by MalexTP** [manilarome/blurredfox#32]
After I installed BlurredFox Theme i didn't see the scrollbar on websites, it's weirddd
![image](https://user-images.githubusercontent.com/24663715/92066570-bfac4380-ed91-11ea-93d6-a3a64bc48718.png)
![image](https://user-images.githubusercontent.com/24663715/92066586-c8047e80-ed91-11ea-88a3-80bdbcfc8e12.png)
![image](https://user-images.githubusercontent.com/24663715/92066543-ac997380-ed91-11ea-8525-a8b3f9c4c4e3.png)
![image](https://user-images.githubusercontent.com/24663715/92066613-deaad580-ed91-11ea-88f9-4fa39ff69967.png)

**Comment by manilarome** [comment]
The instruction's on the README.md. Modify the userContent.css.
