### ISSUE TITLE
Once installed manually it doesn't respond to any interaction.

### ISSUE THREAD

**Issue by VuInicura** [manilarome/blurredfox#37]
I am unable to maximize or drag the window or click into the page or even type. It doesn't respond to anything. It does appear correctly and Firefox is indeed running and is not frozen, it's just whenever I try to do anything it just doesn't respond.

**Comment by eromatiya** [comment]
What is your OS? Windows10?

**Comment by VuInicura** [comment]
Yes, Windows 10

**Comment by eromatiya** [comment]
Uhm, sorry, but I cannot help you with that. Transparency is broken on windows 10 like I said [here](https://github.com/manilarome/blurredfox#notes). The only alternative is to switch colorscheme and use the [solid](https://github.com/manilarome/blurredfox/blob/6976b5460f47bd28b4dc53bd093012780e6bfed3/userChrome.css#L14) ones and you probably don't want that. So yeah, sorry. Will close this now.
