### ISSUE TITLE
Option for older style (i.e. not expecting vertical title bar)

### ISSUE THREAD

**Issue by podiki** [manilarome/blurredfox#39]
Love the theme, thanks! I was hoping an option can be made (via install script, different css files to use, commented in one css, ...) to have the older style of this theme, with blurred transparency from the content area through to the top. In other words, without the sort of striping now that looks great for having the vertical bar on the side, but doesn't quite match without it. In my case, I don't have window borders or decorations.

**Comment by eromatiya** [comment]
> to have the older style of this theme

Sorry but it is what it is. If you want an older style of this theme, you can just `git reset --hard` or something.

So yeah. Thanks for suggestion tho!
