### ISSUE TITLE
No scrollbar

### ISSUE THREAD

**Issue by gabrc52** [manilarome/blurredfox#4]
I don't know if this is a bug or a feature, but I use scrollbars to get an idea of how much I've read and how much is still left

**Comment by manilarome** [comment]
I'll look into it and get back to you.

**Comment by manilarome** [comment]
Hello, to enable/show the scrollbar again, comment this [line](https://github.com/manilarome/blurredfox/blob/8dfd658e48580b5ffecdc6bf395bf3f133aa2894/userContent.css#L12). You can also enable the scrollbar by commenting this [line](https://github.com/manilarome/blurredfox/blob/8dfd658e48580b5ffecdc6bf395bf3f133aa2894/userContent.css#L17). 

Thanks! Closing this now. :)

**Comment by gabrc52** [comment]
Thanks a lot!
