### ISSUE TITLE
When a video is playing, the tab of the video become purple.

### ISSUE THREAD

**Issue by marcantoinem** [manilarome/blurredfox#41]
Everything is explained in the title. Here's a picture of what it look. 
![image](https://user-images.githubusercontent.com/50534281/93829159-ffe93e00-fc3a-11ea-8fdc-183a6609ff8d.png)

**Comment by eromatiya** [comment]
Yes. That's not an issue but a feature. Here's the relevant code: https://github.com/manilarome/blurredfox/blob/6976b5460f47bd28b4dc53bd093012780e6bfed3/parts/tabbar.css#L200-L203

So yeah, closing this now!
