### ISSUE TITLE
Blur overflow

### ISSUE THREAD

**Issue by AshutoshFreak** [manilarome/blurredfox#43]
I'm getting extra blur on right and bottom edges when I disable Title bar. My guess is it has something to do with window borders. I'm using KDE. Is there any way to fix it? Thanks in advance!

![Screenshot_20201006_001831](https://user-images.githubusercontent.com/44664726/95121698-07e1cb80-076d-11eb-8abd-c0f0c4b30f5e.png)

**Comment by eromatiya** [comment]
Can't seem to reproduce this.

![image](https://user-images.githubusercontent.com/40349590/95159903-cf280d80-07d1-11eb-9113-90d09331d011.png)

**Comment by RaineGit** [comment]
Same problem here.
P.S. The toolbar's transparency doesn't work either as you can see in the screenshot.
OS: Ubuntu 20.04.2 LTS x86_64
DE: Plasma
WM: KWin
<img src="https://user-images.githubusercontent.com/25404214/116580489-b620ae80-a913-11eb-9631-36bac99f3f77.png" width="500">
After enabling the title bar, the blur overflow goes away:
<img src="https://user-images.githubusercontent.com/25404214/116581382-90e07000-a914-11eb-93f4-d526e211c5b6.png" width="500">

**Comment by RaineGit** [comment]
> Same problem here.
> P.S. The toolbar's transparency doesn't work either as you can see in the screenshot.
> ...

After downgrading to firefox 87 (I was using firefox 88) the toolbar's transparency works, but the blur overflow is still there:
<img src="https://user-images.githubusercontent.com/25404214/116740549-78945200-a9f5-11eb-8cbb-b97ae2d57f40.png" width="500">
