### ISSUE TITLE
Round edge tabs

### ISSUE THREAD

**Issue by watusshi** [manilarome/blurredfox#44]
[
![Screenshot_20201006_112734](https://user-images.githubusercontent.com/25576806/95230042-ef9e9a80-07c6-11eb-8ac8-c1eb0fdf99fb.png)
](url)

Just installed the theme and for some reason my tabs are not rounded as I saw in the preview screenshot!

**Comment by eromatiya** [comment]
It's because you're in compact mode. Use normal or touch to have the rounded corners. Closing this now! :)
