### ISSUE TITLE
Letters overlapping in the searchbar

### ISSUE THREAD

**Issue by LennyD3al** [manilarome/blurredfox#45]
The the look great, but my searchbar is a little bit wonky 
![20201105_122355](https://user-images.githubusercontent.com/38808406/98236144-2a7d2500-1f63-11eb-8f76-8a56d879e423.png)

**Comment by eromatiya** [comment]
[Disable font ligature](https://wiki.archlinux.org/index.php/Font_configuration/Examples#Disable_ligatures_for_monospaced_fonts) or change your system font. I can't really do anything about this so closing this now. Goodluck!
