### ISSUE TITLE
URL is blurred after clicking off

### ISSUE THREAD

**Issue by ThePotato10** [manilarome/blurredfox#46]
After clicking on the URL bar on the top of the page, it is blurred, kinda looks like a mix of the highlighted and unhighlighted versions mixed together. It fixes itself once I interact with the computer in any way

I installed by running `curl -fsSL https://raw.githubusercontent.com/manilarome/blurredfox/script/install.sh |
bash -s -- stable`

My system is Manjaro Linux with Gnome, running version 83.0 of Firefox stable

**Comment by eromatiya** [comment]
Is this what you mean?

![2020-11-25_07-47](https://user-images.githubusercontent.com/40349590/100164378-adeebe00-2ef2-11eb-85ac-0be2add7376b.png)

If yes, then it's normal. You can change/remove it by changing the value of `backdrop-filter`. If no, can you please send a screenshot?

**Comment by ThePotato10** [comment]
![image](https://user-images.githubusercontent.com/63891976/100172468-68040c80-2e96-11eb-90a3-220fab63f425.jpeg)

It fixes itself once I click somewhere else in the browser

**Comment by eromatiya** [comment]
Hmm I think it's an issue with gnome's compositor or probably firefox's. The theme is not responsible for compositing, it just changes the appearance. And I can't also reproduced this on my KDE Plasma.

**Comment by ThePotato10** [comment]
Alright then. Thanks for your work
