### ISSUE TITLE
[Question] Transparent about:newtab

### ISSUE THREAD

**Issue by 0xVR** [manilarome/blurredfox#47]
I know that this is only for firefox's UI elements, but I was wondering if there was a way to chane the dark background of about:newtab to transparent? I'm assuming it's possible since the window is transparent when loading a website

**Comment by shaansubbaiah** [comment]
Were you able to figure this out?

**Comment by 0xVR** [comment]
Nope, I assume it's not possible since I tried changing a bunch of stuff myself to no avail
