### ISSUE TITLE
Right click menu hardly visible

### ISSUE THREAD

**Issue by Vinhocent** [manilarome/blurredfox#6]
![image](https://user-images.githubusercontent.com/17696462/84066388-d5c58600-a993-11ea-8b79-a8fb1421d154.png)

Right click is hard to see. (Note: it was hard to take the screenshot as it would fade out so the screenshot isn't completely accurate) 

Add option to change the text to white on the context menu?

**Comment by manilarome** [comment]
Can't seem to reproduce this. What's your firefox version? And are you using the dark theme?

![image](https://user-images.githubusercontent.com/40349590/84090034-2fc15c80-aa23-11ea-87d9-2c38f831089c.png)

**Comment by Vinhocent** [comment]
Hmmm, I'm on Firefox 77.0.1 for Ubuntu, running KDE plasma and yeah, I'm using the dark theme. Is there an option in the userchrome to change the color of the context menu text?

**Comment by manilarome** [comment]
> Is there an option in the userchrome to change the color of the context menu text?

Yes. You can change the its css variables [here](https://github.com/manilarome/blurredfox/blob/20804633c1990b4a2db235eb4ffd0d8c7b25c013/userChrome.css#L38-L39). You can also change its css properties [here](https://github.com/manilarome/blurredfox/blob/20804633c1990b4a2db235eb4ffd0d8c7b25c013/userChrome.css#L538-L558).

**Comment by Vinhocent** [comment]
```

menupopup, popup,
popup > menu > menupopup,
menupopup > menu > menupopup {
	-moz-appearance: none !important;
	background: var(--bf-menupopup-bg) !important;
	border: 0px !important;
	border-radius: 4px !important;
        color:#fff !important;
	padding: 2px 0px 2px 0px  !important;
}

```

ended up fixing it by adding ` color:#fff !important;`, I'm not sure why it didn't work on my side though.

**Comment by manilarome** [comment]
Glad you fixed it! I also applied your solution to this commit https://github.com/manilarome/blurredfox/commit/0e8818a039cba63f51d9cea93e54bc738994e648 just in case. Thanks! Closing this now!
