### ISSUE TITLE
What is the task switcher applet you use?

### ISSUE THREAD

**Issue by Jing-Linux** [manilarome/blurredfox#61]
I just saw the screenshot in redesign branch, and I am really interested in that tab-like task switcher. Can you tell me how to set up it? And maybe if you can, can you tell me how do you move the window's title bar to the left?

**Comment by Mange** [comment]
I'm not the maintainer, but I could perhaps help triage this a bit.

> I just saw the screenshot in redesign branch, and I am really interested in that tab-like task switcher.

I cannot see one in the screenshots folder. Maybe you could link to the screenshot in question?

> […] can you tell me how do you move the window's title bar to the left?

The README on the `master` branch used to document this. This is a feature of Awesome WM and not something that can be done inside Firefox. It's a window manager's responsibility.

**Comment by Jing-Linux** [comment]
> I cannot see one in the screenshots folder. Maybe you could link to the screenshot in question?

https://raw.githubusercontent.com/manilarome/blurredfox/redesign/scrot/default.webp

At the top bar, there are tabs.

**Comment by Mange** [comment]
Aha. That looks like a customized [AwesomeWM tasklist](https://awesomewm.org/doc/api/classes/awful.widget.tasklist.html).

See [manilarome's dotfiles](https://github.com/manilarome/the-glorious-dotfiles) if you want to see how they are done.

I suspect it's this component:
https://github.com/manilarome/the-glorious-dotfiles/blob/f3c7cae9ec45e5b3fc8ef93063df23ccbaab3838/config/awesome/floppy/widget/task-list/init.lua

**Comment by Jing-Linux** [comment]
Wow. Thanks for help man.
