### ISSUE TITLE
[Feature Request] Add LibreWolf compatibility.

### ISSUE THREAD

**Issue by allusive-dev** [manilarome/blurredfox#72]
I know a lot of people including myself use LibreWolf over FireFox. If you could add compatibility for LibreWolf that would be greatly appreciated.

**Comment by lasersPew** [comment]
> I know a lot of people including myself use LibreWolf over FireFox. If you could add compatibility for LibreWolf that would be greatly appreciated.

For this I don't think that the developer can help with that. See this: [Reddit](https://www.reddit.com/r/LibreWolf/comments/u0hx0t/comment/i4917od/?utm_source=share&utm_medium=web2x&context=3)

> yes userChrome customization works identical to how it does in Firefox, nothing different about it in librewolf

More Info with the fixes they used: [Reddit(Same post)](https://www.reddit.com/r/LibreWolf/comments/u0hx0t/customization_with_css/?utm_source=share&utm_medium=web2x&context=3)
